apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ProfiseeDemo
  region: us-east-1

managedNodeGroups:
  - name: linux-ng
    instanceType: t2.medium
    minSize: 1
    volumeSize: 100
    availabilityZones: ["us-east-1a"]
  - name: windows-ng
    instanceType: m5.xlarge
    minSize: 1
    volumeSize: 100
    availabilityZones: ["us-east-1a"]
    amiFamily: WindowsServer2022FullContainer