# SQL Server Configuration
sqlServer:
  # Provide the fully qualified domain name of your SQL server.
  name: "<SQL_SERVER_FULLY_QUALIFIED_DOMAIN_NAME>"
  
  # Name of the database to be used.
  databaseName: "<DATABASE_NAME>"
  
  # Username for SQL server authentication.
  userName: "<SQL_USERNAME>"
  
  # Password for SQL server authentication.
  password: "<SQL_PASSWORD>"

# Profisee Runtime Configuration
profiseeRunTime:
  # Set to 'true' if you want to use Let's Encrypt for SSL, 'false' otherwise.
  useLetsEncrypt: false
  
  # Email or account of the first super user to be registered with Profisee.
  adminAccount: "<FIRST_SUPER_USER_EMAIL_OR_ACCOUNT>"
  
  # File Repository Configuration
  fileRepository:
    accountName: "<ACCOUNT_NAME>"
    
    # The user name used to access the file repository.
    userName: "user manager\\containeradministrator"
    
    password: "<PASSWORD>"
    logonType: "NewCredentials"
    
    # The location on your server where files will be stored.
    location: "c:\\fileshare"
    
    # The name of your file share.
    fileShareName: "<FILE_SHARE_NAME>"
  
  # External DNS Configuration
  # URL to your Profisee endpoint (e.g., https://profiseemdm.mycompany.com)
  externalDnsUrl: "<PROFISEE_ENDPOINT_URL>"
  
  # Web URL to your Profisee endpoint (e.g., profiseemdm.mycompany.com)
  externalDnsName: "<PROFISEE_ENDPOINT_WEB_URL>"
  
  # OIDC (OpenID Connect) Configuration
  oidc:
    # The name of your authority (e.g., Okta, Azure Active Directory)
    name: "<AUTHORITY_NAME>"
    
    # The URL of your authority (e.g., https://mycompany.okta.com/oauth2/default)
    authority: "<AUTHORITY_URL>"
    
    # Your authority client ID.
    clientId: "<AUTHORITY_CLIENT_ID>"
    
    # Your authority client secret.
    clientSecret: "<AUTHORITY_CLIENT_SECRET>"
    
    # The claim name for the username.
    usernameClaim: "<USERNAME_CLAIM_NAME>"
    
    # The claim name for the user ID.
    userIdClaim: "<USER_ID_CLAIM_NAME>"
    
    # The claim name for the first name.
    firstNameClaim: "<FIRST_NAME_CLAIM_NAME>"
    
    # The claim name for the last name.
    lastNameClaim: "<LAST_NAME_CLAIM_NAME>"
    
    # The claim name for the email.
    emailClaim: "<EMAIL_CLAIM_NAME>"
  
  # The number of cluster nodes to be used.
  clusterNodeCount: 1

# Cluster Node Configuration
clusterNode:
  limits:
    cpu: 1000
    memory: 10T
  requests:
    cpu: 1
    memory: 1000M

# Image Configuration
image:
  # The registry where your images are stored.
  registry: "profisee.azurecr.io"
  
  # The repository for your images.
  repository: "profiseeplatform"
  
  # The tag for your images.
  tag: "2023r2.0-133022-win22"
  
  # Authentication for your image registry.
  auth: |
    {
       "auths":{
          "profisee.azurecr.io":{
             "username":"<IMAGE_REGISTRY_USERNAME>",
             "password":"<IMAGE_REGISTRY_PASSWORD>",
             "email":"support@profisee.com",
             "auth":"<IMAGE_REGISTRY_AUTH_TOKEN>"
          }
       }
    }

# License Configuration
# Provide the license string as supplied by Profisee support.
licenseFileData: "<LICENSE_STRING>"

# Scripts to be run before and after initialization.
preInitScriptData: "<BASE64_ENCODED_PRE_INIT_SCRIPT>"
postInitScriptData: "<BASE64_ENCODED_POST_INIT_SCRIPT>"

# OIDC File Configuration
oidcFileData: |
  {}  # Add your OIDC configuration as a JSON object here.

# TLS Certificate Configuration
tlsCert: |
  -----BEGIN CERTIFICATE-----
  <ADD_CERTIFICATE_STRING_HERE>
  -----END CERTIFICATE-----

tlsKey: |
  -----BEGIN PRIVATE KEY-----
  <ADD_CERTIFICATE_KEY_STRING_HERE>
  -----END PRIVATE KEY-----

# Cloud Provider Configuration
cloud:
  azure:
    isProvider: false
      
  aws:
    isProvider: true
    ebsVolumeId: "<AWS_EBS_VOLUME_ID>"
      
  google:
    isProvider: false