AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation Template for EKS Cluster and Associated Resources"

Resources:
  # VPC
  VPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: "10.0.0.0/23"
      EnableDnsSupport: true
      EnableDnsHostnames: true

  # Public Subnet for Nginx
  PublicSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref VPC
      CidrBlock: "10.0.0.0/24"
      MapPublicIpOnLaunch: true
      AvailabilityZone: "us-east-1b"

  # First Private Subnet for Other Resources
  PrivateSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref VPC
      CidrBlock: "10.0.1.0/25"
      MapPublicIpOnLaunch: false
      AvailabilityZone: "us-east-1a"

  # Second Private Subnet for Other Resources and DB Subnet Group
  PrivateSubnet2:
    Type: "AWS::EC2::Subnet"
    Properties:
      VpcId: !Ref VPC
      CidrBlock: "10.0.1.128/25"
      MapPublicIpOnLaunch: false
      AvailabilityZone: "us-east-1c"

  # Security Group for EKS
  EKSSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Security group for EKS cluster"
      VpcId: !Ref VPC

  # IAM Role for EKS Cluster
  EKSClusterRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "eks.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"

  # EKS Cluster
  EKSCluster:
    Type: "AWS::EKS::Cluster"
    Properties:
      Name: "ProfiseeDemo"
      Version: "1.27"
      RoleArn: !GetAtt EKSClusterRole.Arn
      ResourcesVpcConfig:
        SecurityGroupIds: [ !Ref EKSSecurityGroup ]
        SubnetIds: [ !Ref PrivateSubnet, !Ref PrivateSubnet2 ]

  # Linux Node Group
  LinuxNodeGroup:
    Type: "AWS::EKS::Nodegroup"
    Properties:
      ClusterName: !Ref EKSCluster
      NodegroupName: "linux-ng"
      ScalingConfig:
        MinSize: 2
        MaxSize: 3
        DesiredSize: 2
      InstanceTypes: ["t2.medium"]
      Subnets: [ !Ref PrivateSubnet, !Ref PrivateSubnet2 ]
      NodeRole: !GetAtt NodeInstanceRole.Arn
      DiskSize: 100

  # Windows Node Group
  WindowsNodeGroup:
    Type: "AWS::EKS::Nodegroup"
    Properties:
      ClusterName: !Ref EKSCluster
      NodegroupName: "windows-ng"
      ScalingConfig:
        MinSize: 1
        MaxSize: 3
        DesiredSize: 2
      InstanceTypes: ["m5.xlarge"]
      Subnets: [ !Ref PrivateSubnet, !Ref PrivateSubnet2 ]
      NodeRole: !GetAtt NodeInstanceRole.Arn
      DiskSize: 100
      AmiType: "WindowsServer2022FullContainer"

  # Node Instance Role
  NodeInstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "ec2.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"
        - "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
        - "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"

  # ACM Certificate
  ACMCertificate:
    Type: "AWS::CertificateManager::Certificate"
    Properties:
      DomainName: "yourdomain.com"
      ValidationMethod: "DNS"

  # Ingress Controller Security Group
  IngressControllerSetup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      VpcId: !Ref VPC
      GroupDescription: "Security group for Nginx Ingress Controller"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
          CidrIp: "0.0.0.0/0"
        - IpProtocol: "tcp"
          FromPort: 443
          ToPort: 443
          CidrIp: "0.0.0.0/0"

  # RDS SQL Server Instance
  RDSInstance:
    Type: "AWS::RDS::DBInstance"
    Properties:
      Engine: "sqlserver-ex"
      DBInstanceClass: "db.t3.xlarge"
      DBInstanceIdentifier: "profisee"
      MasterUsername: "sqladmin"
      MasterUserPassword: "YOURPASSWORD"  # Ensure this is secured
      AllocatedStorage: 20
      PubliclyAccessible: false
      DBSubnetGroupName: !Ref DBSubnetGroup
      VPCSecurityGroups:
        - !Ref EKSSecurityGroup

  # DB Subnet Group for RDS
  DBSubnetGroup:
    Type: "AWS::RDS::DBSubnetGroup"
    Properties:
      DBSubnetGroupDescription: "Subnet Group for RDS"
      SubnetIds:
        - !Ref PrivateSubnet
        - !Ref PrivateSubnet2

Outputs:
  EKSClusterArn:
    Description: "ARN of the EKS Cluster"
    Value: !GetAtt EKSCluster.Arn

  PublicSubnetId:
    Description: "ID of the public subnet"
    Value: !Ref PublicSubnet

  PrivateSubnetId:
    Description: "ID of the first private subnet"
    Value: !Ref PrivateSubnet

  PrivateSubnet2Id:
    Description: "ID of the second private subnet"
    Value: !Ref PrivateSubnet2

  RDSInstanceEndpoint:
    Description: "Endpoint of the RDS instance"
    Value: !GetAtt RDSInstance.Endpoint.Address